### ISSUE TITLE
i18n via config object

### ISSUE THREAD

**Issue by jmdavid** [ghiscoding/aurelia-slickgrid#2]
**I'm submitting a feature request**

Suggestion: it would be nice to have all labels that are actually hardcoded in application (ex. 'Force fit columns', 'Synchronous resize', 'Page n of n', 'items per page', 'n-n of n items') configurables via configuration object.

**Comment by ghiscoding** [comment]
The pagination and other text that are embedded in my lib will be in the form of translation (possibly `i18n`, I just didn't have the time to look at that yet). My plan would be to have JSON files containing the translations (`en.json`, `fr.json`, ...)

For the ones showing up in the column picker (right+click menu), it will be hard (might not even be feasible) since I use directly the [Column Picker Controls](https://github.com/6pac/SlickGrid/blob/master/controls/slick.columnpicker.js) from `SlickGrid` directly and they wrote them in English, and so I don't have direct access to change the text.

**Comment by ghiscoding** [comment]
Got most of the implementation done, however I need an answer on this [SO](https://stackoverflow.com/questions/47741878/how-to-support-multiple-i18n-endpoint-in-aurelia) question before going further.

**Comment by ghiscoding** [comment]
I'm looking at implementing `i18n` and I was wondering if you know how to pass translation params via code (ViewModel)? It would be nice to have a dynamic translation working as well. So if we use the View, we can pass it via `t-params`, I'm looking for the equivalent of that in the VM.

**Comment by ghiscoding** [comment]
This is now released with [version 1.1.0](https://github.com/ghiscoding/aurelia-slickgrid/releases/tag/v1.1.0)
