### ISSUE TITLE
OData not working and failing on 'statistics"

### ISSUE THREAD

**Issue by si2030** [ghiscoding/aurelia-slickgrid#212]
Hi there,

I did ask an exploratory [question ](https://github.com/ghiscoding/aurelia-slickgrid/issues/196) on pagination and the idea was to get OData working on the server and then use the OData example to send through fetch queries to populate the dataset however I am having trouble getting this to work correctly having got OData to work and send back OData responses from the server.

I am getting the error:
`Uncaught (in promise) TypeError: Cannot set property 'statistics' of undefined
    at AureliaSlickgridCustomElement.<anonymous> (aurelia-slickgrid.js:496)
    at step (aurelia-slickgrid.js:48)
    at Object.next (aurelia-slickgrid.js:29)
    at fulfilled (aurelia-slickgrid.js:20)`

My code is as follows and is a simple 5 column grid using OData.

```
        import { Aurelia, PLATFORM, autoinject } from "aurelia-framework";
        import { Router } from "aurelia-router";
        import { HttpClient, json } from 'aurelia-fetch-client';
        import { EventAggregator } from 'aurelia-event-aggregator';
        import {
            AureliaGridInstance,
            Column,
            FieldType,
            Formatters,
            Filters,
            GridOdataService,
            GridOption,
            OperatorType,
            SortDirection,
            Statistic,
        } from 'aurelia-slickgrid';

        import { MessagePayload } from '../../../../services/messages/messages'
        import { AuthService } from '../../../../services/auth/auth-service'

        const defaultPageSize = 20;
        const sampleDataRoot = 'src/examples/slickgrid/sample-data';

        @autoinject()
        export class ClientList {
            title = 'Client List';
            subTitle = `
        Click on a client to examine and or edit.
        <br/>
        `;
            aureliaGrid: AureliaGridInstance;
            columnDefinitions: Column[];
            gridOptions: GridOption;
            dataset = [];
            statistics: Statistic;

            odataQuery = '';
            processing = false;
            status = { text: '', class: '' };

            constructor(
                private http: HttpClient,
                private authService: AuthService,
                private router: Router) {
                // define the grid options & columns and then create the grid itself
                this.defineGrid();
            }

            aureliaGridReady(aureliaGrid: AureliaGridInstance) {
                this.aureliaGrid = aureliaGrid;
            }

            defineGrid() {
                this.columnDefinitions = [
                    { id: 'clientNo', name: 'Client No.', field: 'clientNo', sortable: true, type: FieldType.string, filterable: true, filter: { model: Filters.compoundInput } },
                    { id: 'company', name: 'Company', field: 'company', sortable: true, formatter: Formatters.checkmark },
                    { id: 'clientLastName', name: 'Last Name', field: 'clientLastName', sortable: true, type: FieldType.string, filterable: true, filter: { model: Filters.compoundInput } },
                    { id: 'clientFirstName', name: 'First Name', field: 'clientFirstName' },
                    { id: 'mobilePhone', name: 'Mobile Ph.', field: 'mobilePhone', sortable: true, type: FieldType.string, filterable: true, filter: { model: Filters.compoundInput } },


                ];

                this.gridOptions = {
                    enableAutoResize: true,
                    autoResize: {
                        containerId: 'demo-container',
                        sidePadding: 15
                    },
                    enableCellNavigation: true,
                    enableFiltering: true,
                    enableRowSelection: true,
                    pagination: {
                        pageSizes: [10, 20, 50, 100, 500],
                        pageSize: defaultPageSize,
                        totalItems: 0
                    },
                    presets: {
                        // you can also type operator as string, e.g.: operator: 'EQ'

                        sorters: [
                            // direction can be written as 'asc' (uppercase or lowercase) and/or use the SortDirection type
                            { columnId: 'clientNo', direction: 'asc' },
                            { columnId: 'clientLastName', direction: 'asc' },
                            { columnId: 'mobilePhone', direction: 'asc' }
                        ],
                        pagination: { pageNumber: 1, pageSize: 10 }
                    },
                    backendServiceApi: {
                        service: new GridOdataService(),
                        preProcess: () => this.displaySpinner(true),
                        process: (query) => this.getCustomerApiCall(query),
                        postProcess: (response) => {
                            //console.log("RESPONSE: ", response);
                            //this.statistics = response.statistics;
                            this.displaySpinner(false);
                            this.getCustomerCallback(response);
                        }
                    }
                };
            }

            displaySpinner(isProcessing) {
                this.processing = isProcessing;
                this.status = (isProcessing)
                    ? { text: 'processing...', class: 'alert alert-danger' }
                    : { text: 'done', class: 'alert alert-success' };
            }

            getCustomerCallback(data) {
                // totalItems property needs to be filled for pagination to work correctly
                // however we need to force Aurelia to do a dirty check, doing a clone object will do just that
                console.log("...AND HERE!");
                this.gridOptions.pagination.totalItems = data['totalRecordCount'];
                this.gridOptions = { ...{}, ...this.gridOptions };
                if (this.statistics) {
                    this.statistics.totalItemCount = data['totalRecordCount'];
                }

                // once pagination totalItems is filled, we can update the dataset
                this.dataset = data['items'];
                this.odataQuery = data['query'];
            }

            getCustomerApiCall(odataQuery) {
                // in your case, you will call your WebAPI function (wich needs to return a Promise)
                // for the demo purpose, we will call a mock WebAPI function
                const headers = this.authService.header();

                return fetch(`/api/Client/Index?${odataQuery}`, {
                    method: "GET",
                    headers
                }).then(response => {
                    return response.json();
                });
            }
        }
```

For completeness here is the controller in the dotnet app:

	   [HttpGet("Index", Name = "ClientIndex")]
	   [EnableQuery()]
		public IEnumerable<Client> GetClients() {
			return _context.Clients;
		}

The dataset coming back from this is:

dataset:  
![DATASET](https://user-images.githubusercontent.com/16522902/62345187-9852c980-b534-11e9-8580-006248cc533e.png)

I see that it is erroring on statistics as if the return set should have "totalRecordCount" and it doesnt so its identifying that as undefined I think..

I am not sure how to get this working once but if I can I believe I can use it throughout the app which is what I want to do..

So, what am I missing? Its using the query created by slickgrid etc...

**Comment by ghiscoding** [comment]
The `statistics` like I told you the other day are just statistics metadata (like how long it took to run, how many rows, etc...) and it works ok when using GraphQL (which is what we use) but I might have forgot a property check or something. Can you click on the line console log line that says `aurelia-slickgrid.js:496`, I need to see exactly where the error comes from in the lib.

**Comment by si2030** [comment]
Hey thanks for having a look at this so quickly.. appreciated. I have taken a screen scrap of the code which shows the error underlined.  The other thing I noted was with the return data set. I could not find any information on "totalRecordCount".. and this was not requested in the query however I not across this like you are and you might have a different take etc

![SG STAT PROBLEM](https://user-images.githubusercontent.com/16522902/62404880-5a5cb080-b5db-11e9-89cc-90fce08dda28.png)

**Comment by ghiscoding** [comment]
Well by looking at the code, technically speaking `processResult` should not and cannot be null or undefined since that is the result of the fetch promise. For this to work, `process` has a to a `Promise` that must return a value (async/await). If I look at your code, it looks like the method `getCustomerApiCall` is returning well hmmm something undefined I think. I say this because you return `fetch` but you should be returning `this.fetch`, else `fetch` is just undefined I think since you're not using the fetch from the class itself.

**Comment by si2030** [comment]
Thanks for having a look.. so I did miss that and duly changed it..

I ran it again but appear to be getting the same error.. I have taken a screen shot of the console for your info..

Its clear I am getting the data back but it's failing after that.. as I mentioned before you know this intimately where as I dont so it might be (most likely be) something I have done..

Simon

```
	getCustomerApiCall(odataQuery) {
		// in your case, you will call your WebAPI function (wich needs to return a Promise)
		// for the demo purpose, we will call a mock WebAPI function
        console.log("QUERY: ", odataQuery);
		const headers = this.authService.header();

        return this.http.fetch(`/api/Client/Index?${odataQuery}`, {
            method: "GET",
            headers
        }).then(response => {
            response.json();
        });
```
![SG STAT PROBLEM 2](https://user-images.githubusercontent.com/16522902/62406690-e3331680-b5f2-11e9-8e25-6d9fd353b15f.png)

**Comment by ghiscoding** [comment]
Your code is still not correct, you should really use what is in the Wiki and that would have worked. Your problem is that you do the `response.json()` but you are not returning it, hence the `processResult` (that comes from the error in the console, is undefined. 

This line from the wiki
`return this.http.fetch(`/api/customers?${odataQuery}`).then(response => response.json());`

is **NOT** the same as your line of code. Your line **DOES NOT** return
```ts
....
.then(response => {
    response.json();
});
```
if you want to keep multiline, then it should be 
```ts
....
.then(response => {
    return response.json();
});
```

You have to know that when you write a 1 liner (what I wrote in the Wiki)  `...then(response => response.json()` it does the `return response.json()` for you. This is basic ES6 syntax, I suggest you to maybe re-read this portion of the ES6 syntax. 

I did this kind of errors a bunch of time in my code, but please review your code before posting this as an issue (when it is not).

**Comment by si2030** [comment]
I'm not sure of your name however I am very appreciative of your help here. I do confess I am no gun at this but self taught and a hack but not stupid.. I get the frustration so I appologise for being slow... Its now supplying statistics but other errors persist that, I think are not something to do with you..

You do suggest not posting stuff that is not a bug etc however you have asked for ways on making the documentation better etc. For those if us that are bringing up the rear and do need help getting started it would be good to have another option rather than just the three (Bug Report, Feature Request and General) that you currently have. Like the Aurelia discourse, you might consider a "Help" option and those questions asked there would serve the purpose of a) Helping individuals like me and b) supplying context to issues that beginners experience. Seeing examples like that and where people like me screw up can be invaluable.. Its more work though.. just saying.. anyway thanks for not getting completely shitty with me.

Its now working but

**Comment by ghiscoding** [comment]
You might have misunderstand what I meant to say, I don't want to be rude or anything, it's just that I get a lot of these questions every single week (95% of these comes from the Angular-Slickgrid which as a lot more users), if you are curious you can see the list of all [questions](https://github.com/ghiscoding/Angular-Slickgrid/issues?q=is%3Aissue+is%3Aclosed+label%3Aquestion) I got in the Angular-Slickgrid repo. 

But the thing is, I'm a single man on these 2 repos and I'm passing anywhere from 5 to 15 hours of work per week on these 2 repos and I do this for free because I like this lib. I'm also the biggest contributor on the SlickGrid core lib itself. I wish I had contributors and people helping me to answers questions like yours but I just don't, so it all falls back on me trying to review and answer all these issues, which 80% of these issues are actually just questions. For every issue or question, I need to investigate or wrap my head around it and try to understand it, for example your question I spent maybe 30min to investigate what the problem could be (which is hard without a working demo), then answer to the user and by the time I'm done, the day is long gone. 

So again I didn't want to be rude, but you have to understand that I spend a lot of time on these libraries, which is free and open source for everyone to use but yeah it's hard to maintain sometimes. Hope you understand where I come from... also I was investigating a bug in the lib for the past 2 hours, so my frustration is more around these bugs, I'd like the lib to be bug free but that is also hard, however I did improve on unit test side.

**Comment by si2030** [comment]
I am really sorry regarding my question and the fact it was such a stupid error - i'd be frustrated. The last thing I want to do is cause people like you to allocate time you cant get back. That said I really want to use your work to decorate my project.. Its excellent.

To this end I thought under the circumstances I would throw you a few coffees.. as I am still struggling with this implementation as its failing on value converters now sadly... however once I have it working once I will be sorted across the whole project.. again sorry to bother. ;) 

PS whilst I want this project done its fine to leave me go a few days (fix the bugs) as I am it on the project and not relying on this for a job..

**Comment by ghiscoding** [comment]
It's all good we are all friends, sorry about the other [answer](https://github.com/ghiscoding/aurelia-slickgrid/issues/212#issuecomment-517897833), I was in the middle of troubleshooting and tired at same time, so that doesn't help to reply to others. The goal of that answer was more to make you understand the ES6 syntax and I might have put a bit too much in the answer.

Also, just to make sure you understand how the OData works in the Example 5 that I've done, your REST API **must** return an object, like on this [line](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/examples/slickgrid/example5.ts#L264) in the example. If you are returning directly the array of data, then you'll get the error in the console that you provided on top. So why an object? Because I'm expecting the users to return an object with the items or dataset **and** the total count of items. The total count of items is important for the pagination to work. So in the demo it returns this object `{ items: [ /** data **/, totalRecordCount: 100 }`, the name of the properties (name & totalRecordCount) is all up to you, you can put whatever you want but you must use the correct property names in your `getCustomerCallback()` method (which is called by the `postProcess`) on this [line](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/examples/slickgrid/example5.ts#L130) of the example. I think that this explanation might be missing in the Wiki, so I'll add that in the coming days. 

I'll see if I have time to do a real live demo with OData queries from a live OData server, all I found so far are this [OData v4 Service](https://www.odata.org/odata-services/) and [OData v3 Payload Example](https://blogs.msdn.microsoft.com/leohu/2013/10/04/odata-and-json-payload-examples/) but they both lack the total record count, so that won't work good with the grid pagination, best I could do for the demo is to calculate the returned data array size but that is not the correct total to return. If you have better OData example with more data, please provide, I find these examples I found quite small to play with

**Comment by si2030** [comment]
Hey man I know you are really busy but on the off chance you might find a chance to have a look at this. I decided to continue with this issue as I believe its a statistics issue.

Two things.. It turns out that OData for asp.net Core does not return the total items and using count=true etc also doesnt work. This is not your problem so I hard coded the value just to get statistics to work for total item count.

My issue as mentioned above is that its got another error re valueconverters. Is there a package I should have and that I haven't included - just asking..

Here is the screen dump:

![SG STAT PROBLEM 3](https://user-images.githubusercontent.com/16522902/62620564-00524700-b95d-11e9-9006-2ad6688a6b76.png)

Here is a close up of the error expanded.

![SG STAT PROBLEM 5](https://user-images.githubusercontent.com/16522902/62620937-eb29e800-b95d-11e9-99b0-7d540e15d4e4.png)

and here is the section of slickgrid where it first comes up on that list..

![SG STAT PROBLEM 4](https://user-images.githubusercontent.com/16522902/62620972-0137a880-b95e-11e9-88af-d4243eb96f2d.png)

If I can get it working once I should be able to use it all throughout my project.. for those lists that grow large.

..and sorry for bugging you with this..

**Comment by ghiscoding** [comment]
I read the console properly, it looks like you don't have the `dateFormat` Aurelia Value Converter. So you copied the example with the View/ViewModel but you didn't copy everything the examples need, that value converter in particular can be found in this [folder](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/examples/resources/value-converters), basically if you remove the statistics stuff shown in your View (which you probably don't need anyway, it would work without adding that value converter. Those statistics which are shown in the example shows the start time, end time and execution time... so if I were you, I would just delete it from the View and get your demo working. 

> Two things.. It turns out that OData for asp.net Core does not return the total items and using count=true etc also doesnt work. This is not your problem so I hard coded the value just to get statistics to work for total item count.

I know that the OData will only return you the array of data, but for the grid to work properly, you need to provide the total count of items (it can be any variable name you want, but just make sure to use the same name in the `postProcess` callback). If you don't provide this total count, the pagination won't work at all (and you'll probably get some more errors in the console). So your API must return an object that includes the data returned from OData and the total count (as shown below), it is required and must be an object (though I forgot to add this part to the Wiki)

`{ items: [ /** data **/ ], totalRecordCount: 100 }`

Hopefully you'll get that working, once 1 grid is setup, it should be much easier after. 😉

**Comment by ghiscoding** [comment]
You might be interested in this PR #215 for OData version 4, it's merged but not released yet

**Comment by si2030** [comment]
I would be interested :)  How do I download it.. if I can?

**Comment by ghiscoding** [comment]
I'm working on a new feature (Filter by range of search values PR #214), when that is done then I'll release a new version. I'm expecting that to happen during the coming week

**Comment by si2030** [comment]
Hi there, looking on your wiki I found that a couple of links dont work. Its under interface/models specifically column and gridoptions.. cheers.

**Comment by ghiscoding** [comment]
Fixed now
