### ISSUE TITLE
Selectbox height/ Export to csv without headers

### ISSUE THREAD

**Issue by johntom** [ghiscoding/aurelia-slickgrid#260]
Version 2.14.1
1) Is there a way in to increase the height used in the following so more items display in select
 {
      id: 'Account',
      name: 'Account',
      field: 'account',
      filterable: true,
      formatter: Formatters.singleSelect,
      type: FieldType.string,
      excludeFromExport: true,
      editor: {
        collection: this.accounts,
        customStructure: {
          value: 'name',
          label: 'name'
        },

        model: Editors.singleSelect
      },
      minWidth: 100,
      params: {
        formatters: Formatters.collectionEditor
      }
    },
2 Is there a way to exclude coulmn headers from export to csv
Thanks,

**Comment by ghiscoding** [comment]
All the documentation for the Select Filter is in the [Wiki](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Select-Filter), you can change the height and the same goes for the [Export to CSV](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Export-to-File), you can exclude and it's in the wiki.. Just read the Wikis

**Comment by ghiscoding** [comment]
Have you managed to find the answer or do you still need more info? I'd like to close this issue or if the Wiki does not have the answer you are looking for then let me know and I'll update the Wiki and point you in the right direction. Cheers

**Comment by johntom** [comment]
I found the following but still haven't been able to increase the number of rows displayed in a filter collection. 
  filterOptions: {
     autoAdjustDropPosition: True, // by default set to True, but you can disable it
      //   //   position: 'top',
       maxHeight: "400"
     },
I will be working on this Tuesday 11/26 and will get back to you,

**Comment by ghiscoding** [comment]
The multiple/single select Filter uses an external library named `multiple-select.js`, all the options for that library can be found in this TypeScript [interface](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/aurelia-slickgrid/models/multipleSelectOption.interface.ts) and if you use TypeScript you should cast it as that interface to make sure you use only valid options. 

```ts
filterOptions: {
    maxHeight: 400
} as MultipleSelectOption
```
which by the way, **your problem might be** because you wrote it as a **string** but it should be a **number**, you should replace this `maxHeight: "400"` to `maxHeight: 400` which you would have caught with the `filterOptions: { ... } as MultipleSelectOption`

Another possible thing, the defaults used to construct the Multiple Select Filter can be found under that Filter [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/aurelia-slickgrid/filters/selectFilter.ts#L484), it has the `autoAdjustDropHeight: true` and that might cause some problem in your case if you don't have enough space to display it.

**Comment by ghiscoding** [comment]
Closing since this is a question, not an issue with the lib, and it was answered. 
Feel free to reply if that is not the case. 
Cheers
