### ISSUE TITLE
how autoHeight and maxHeight

### ISSUE THREAD

**Issue by crazy365966834** [ghiscoding/aurelia-slickgrid#287]
how can I setting the grid, can implement this case?
if data.length ==1 
  then grid show as real height
if data.length > 10 (def lineHeight = 35, I set maxHeight = 350).
  then grid show ShowVerticalScroll and maxHeight =350px.

I set gridOptions ={
      autoHeight: true,
      autoResize: {
        containerId: "demo-container",
        maxHeight: 350,
      },
    };
it effect when data.length < 10 but not effect when data.length >10.

**Comment by ghiscoding** [comment]
Sorry but this kind of question would be better asked on [Stack Overflow](https://stackoverflow.com/search?q=slickgrid) and to answer your question, I don't know if that would work or not, I never change the height of a grid. The grid options could be changed afterward, so you could maybe do `this.gridOptions.autoHeight = true` after a condition but I'm not sure if that would work, just try it or ask your question on Stack Overflow please.

**Comment by ghiscoding** [comment]
@crazy365966834 actually after some thoughts about your use case, you could call the `resizeGrid()` method from the Resizer Service (that can called at any time), to do that you can take a look at the [Resize - Wiki](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Grid-Auto-Resize#resize-the-grid-with-fixed-dimensions). 

I'll close this issue since I answered it and it's not an issue with the lib but more of a questions. Stack Overflow is still the best places for these kind of questions. 

Please upvote ⭐️ if you like the lib and haven't upvoted yet. 
Cheers
