### ISSUE TITLE
how to use my CustomElement  in CustomEditor

### ISSUE THREAD

**Issue by crazy365966834** [ghiscoding/aurelia-slickgrid#305]
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| aurelia-bootstrapper| ^2.3.2|
| Aurelia-Slickgrid | ^2.16.5|

I write one customElement and configure as globalResources in resources index.js like
```
export function configure(config) {
  config.globalResources([
    PLATFORM.moduleName('./test-input/test-input'),
  ]);
}
```
test-input.html 
```
<template>
  <div>${name}</div>
  <input value.bind="value"/>
</template>

```

test-input.js
```
import {bindable, bindingMode} from 'aurelia-framework';

export class TestInput {
  @bindable({defaultBindingMode: bindingMode.twoWay}) value;

  @bindable name;
}

```

how to code my customEditor and use this model to update record?

**Comment by ghiscoding** [comment]
[Wiki](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Editors#custom-inline-editor), please search the Wikis, I wrote a lot of them and if you can't find an answer then, I would prefer you ask such questions and keep only real issues in here. Thanks

**Comment by ghiscoding** [comment]
I might have misread your question at first, you're trying to do something that is typically not supported in this lib. However I had that working in Angular-Slickgrid, I couldn't get it to work in Aurelia. You can maybe take a look at the [custom-angularComponentEditor](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/custom-angularComponentEditor.ts) and that custom editor is called in this Angular grid [demo](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/src/app/examples/grid-angular.component.ts) with 
```ts
this.columnDefinitions = [
  editor: {
          model: CustomAngularComponentEditor,
          collection: this.assignees,
          params: {
            component: EditorNgSelectComponent,
          }
  },
];
```
The technique is to compile the component (or Custom Element) into html, because that is what SlickGrid requires (remember that Aurelia-Slickgrid is a wrapper of a jQuery library). 

Compiling the Custom Element is something that I do with the Row Detail Extension [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/aurelia-slickgrid/extensions/rowDetailViewExtension.ts#L114) and that service uses some functions I made [createAureliaViewAddToSlot](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/aurelia-slickgrid/services/aureliaUtil.service.ts#L51) to compile an element and add it to a view slot. The main different of why I got it working in Angular-Slickgrid is because I found how to compile an element and add it to the DOM, while in Aurelia I don't know how to do that without an element target. 

So you can try that out but I don't have time to spend on this now. If you get it working, I'd be happy to receive a PR or some instructions on how you got it working. I had started some work in this [commit](https://github.com/ghiscoding/aurelia-slickgrid/commit/47cbf01218b526401ba1122d7f2df45a17cc420c) but I never got it to work and I switched to other features later, so you can maybe start from that commit.

**Comment by ghiscoding** [comment]
... and just to point out, it's a lot easier to just use regular DOM elements with jQuery to bind events like the `keyup`. Going the Aurelia Custom Element route will require some more extra work for Editors and Filters, so in most cases you're much better with regular DOM elements.

**Comment by ghiscoding** [comment]
I added a new [Example 26](https://ghiscoding.github.io/aurelia-slickgrid/#/slickgrid/example26) which have both Custom Editors & Filters coming from an Aurelia Custom Elements, the 2nd column "Assignee" is the column that uses both (it's a simple select dropdown created as an Aurelia Custom Elements [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/examples/slickgrid/editor-select.ts)) and you need to create a Custom Editor like [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/examples/slickgrid/custom-aureliaViewModelEditor.ts) and use that Custom Editor in your column definition like [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/examples/slickgrid/example26.ts#L125).

Personally it's not straightforward and I don't recommend using Aurelia Custom Elements for Editors/Filters as it adds a lot of boilerplate but at least it's not possible if you really wish to go that route. 

Please upvote if you like the lib, thanks ⭐️

**Comment by plarner30** [comment]
@ghiscoding do you think its possible a future version of aurelia-slickgrid might provide view based usage of custom elements for cell content? I suppose ideally there would be a way for all column / cell definitions to be setup in the view HTML, within the <aurelia-slickgrid tag. Appreciate this is probably asking a lot but wondered how viable this might be? For the project I am working on we are using aurelia-ui-virtualization with custom elements in most cells, and sub views accessed by context menus within a lot of them. So am a little hesitant diving in and refactoring especially if this approach isn't recommended. However obviously it would be great to have the feature set Aurelia Slickgrid offers available, and refactoring into SlickGrid also obviously will help with performance / code organization in all other areas.

**Comment by zewa666** [comment]
I think you summed up your concerns about declarative column definitions pretty well @ghiscoding  . nothing to add to this as if you really need the feature for a specific column Example 26 shows how to do it.

**Comment by plarner30** [comment]
Apologies i think i've overlooked that the way to go about this is to use Custom Editors / Formatters in search of a fast to implement solution based on the development phase of the project i'm working on. The issue is that there is some Aurelia components within the current table cells which are also used in other areas of the app, so it would be ideal to just use the same components inside the SlickGrid cells. Also these cell components have already been tested etc so repurposing them into Editor/Formatter versions would make regressions more likely. I appreciate though that the editor/formatter concept is probably integral to how the filtering/updating... and many other features works so there isn't an going to be a quicker way to transition.

**Comment by ghiscoding** [comment]
The fact is that this lib was created as a wrapper of a JS lib and that won't change and also why you will have to refactor some parts. Should you do the jump is up to you to decide, if all your grids are simple grids then don't go for it but if you do want all the whistle and bells then Aurelia-Slickgrid has you covered, there's a ton of features and it's well tested. 

I have 3 libs related to SlickGrid and now all the main code is in [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal) which is also what I use recently in our Salesforce development, the code is very well tested and I spent **a lot** of time adding full test coverage (3,300 Jest unit tests) and also 500 Cypress E2E tests with plenty of [Examples](https://ghiscoding.github.io/aurelia-slickgrid/#/slickgrid). I used it in a few projects already and it even allowed us to save a lot of money too (we recently replaced a paid datagrid lib to use SlickGrid and they love it, the yearly cost was amazingly huge with a lot less features than SlickGrid). My libs are very well maintained since we use it in Production and whenever I see bugs, I fix them and often do releases with bug fixes & features (I will do another release probably by tomorrow) and I keep adding features for the past 4 years since it exists.

Again it's up to you to decide but the fact will remain that this is a wrapper of a JS lib, it's not (and never will be) a pure Aurelia Component. Things are just coded differently, Custom Formatters is such example. All libs together sums up about ~450 stars but I'm sure there's a lot more people using the lib without staring it (and the original SlickGrid itself has over 6,000 stars)

Good luck and happy coding
