### ISSUE TITLE
Slot for custom footer/header

### ISSUE THREAD

**Issue by zewa666** [ghiscoding/aurelia-slickgrid#424]
Hey there, I'm slowly dipping into parts of the library and so naturally some ideas are coming up :)

What I've seen is that while a custom footer is supported, it essentially takes a bare-bones string with a few modifications.
In my case there might be more that will come into the footer, such as a customized pagination.

So what would you say if the [aurelia-slickgrid custom element](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/src/aurelia-slickgrid/custom-elements/aurelia-slickgrid.html#L35) would expose a named slot for both headers and footers like:

```html
<slot name="slick-header"></slot>
<slot name="slick-footer"></slot>
```

so that the consumer could pump in whatever he likes in those places

```html
<aurelia-slickgrid grid-id="grid2"
                       column-definitions.bind="columnDefinitions2"
                       grid-options.bind="gridOptions2"
                       dataset.bind="dataset2"
                       grid-height="300"
                       grid-width="800">
      <div slot="slick-header">A BIG HEADER</div>
      <div slot="slick-footer">That's my footer</div>
    </aurelia-slickgrid>
```

I'd like to discuss this first with you @ghiscoding but can afterwards provide a PR if you'd like

**Comment by ghiscoding** [comment]
I could reply by saying... I don't know much about `slot` yet since I haven't used them yet but I kinda understand the concept. Would it still produce the Footer by using the `showCustomFooter` flag in the Grid Options? I would like to keep that feature

But yeah if it helps with your use, then yes go ahead and create a PR, I'm open for that. 

However a quick thing to note, I never show the Pagination and Footer at the same time, 1 is supposed to replace the other and so I've put some code to only allow displaying a Footer when Pagination is disabled.

**Comment by zewa666** [comment]
Yeah I've seen that part and it makes perfectly sense not allowing both at the same time. The slot approach is completely different though. In essence you would place a slot in your markup and its content can be defined via the consumer. So essentially just a placeholder. There wouldnt be any config needed. If no content for the slot is provided, its not rendered.

**Comment by zewa666** [comment]
I've created the PR along with a new Example29 page, which should hopefully make clear what I'm after :)

**Comment by ghiscoding** [comment]
The only thing that I see as a potential, and very small, issue is that I have some code to remove the height of the Footer/Pagination  from the auto-resize (if you do use that) and you might have to adjust that manually but that's not a big deal, you might need something like this
```ts
this.gridOptions = {
  autoResize: {
        containerId: 'grid-container',
        bottomPadding: 50
  }
```
oh this makes me think, that is another thing that I use in pixel (the number that is) 😝

**Comment by zewa666** [comment]
so bottomPadding in that case would relate to the size of the slotted footer? What is containerId pointing to?

**Comment by ghiscoding** [comment]
The auto-resize tries to calculate the available size from the div container that you include aurelia-slickgrid inside, `<div id="grid-container"> (that is what the `containerId` is for). 

However, the auto-resize doesn't always work, it could depend on multiple factor that could screw up the calculation, for example in Salesforce, they sometime put the grid in a white box and the auto-resize doesn't seem to take it in consideration and I need to add padding manually. In the example below, if I don't add the extra padding the grid goes outside the white box and I think it also doesn't calculate the footer (where you see "Submit an Idea" and "Log an Issue") either and because of that I need to a bottom padding of 80 and that fixes the example below (actually the Footer showing `1 of 1 items` is a bit too close to the edge, I should probably increase the padding to 85 or something).

Things to note, whatever padding you add to the `autoResize` becomes part of the auto resize calculation, so if for example it calculates that it has 600px available and you provide a `bottomPadding: 80`, it will calculate `600 - 80` and resize the grid to a height of 520px. If you enable the pagination, it will internally add `bottomPadding` to the calculation.

![image](https://user-images.githubusercontent.com/643976/94313167-421cc300-ff4c-11ea-8dad-8dbaf9426734.png)
