### ISSUE TITLE
Aurelia 2 support

### ISSUE THREAD

**Issue by MaximBalaganskiy** [ghiscoding/aurelia-slickgrid#709]
## I'm submitting a Feature request
Are there plans to upgrade to Aurelia 2?

**Comment by ghiscoding** [comment]
I have yet to even try Aurelia 2 and I have no clue what needs to be done to upgrade my lib to support Au2. What would be great is that someone creates a PR with the required changes.

**Comment by ghiscoding** [comment]
@MaximBalaganskiy 
Today is the day, Aurelia-Slickgrid v7.0 now requries Aurelia 2. 
Again a big thanks for the help to migrate to Au2, it would not have been possible with your help 🤝 🥇 

I also published all the Wikis to a new Documentation website by using GitBook (kinda got the idea from Aurelia Docs actually)

**Comment by MaximBalaganskiy** [comment]
@ghiscoding  Nice! Appreciate your effort! Au2 future is getting brighter with this plugin :)

**Comment by ghiscoding** [comment]
@MaximBalaganskiy 
hey I'm actually having a problem with the live demo website on GitHub, I change the base path to empty string but it still fill in the `base href="/"` which is wrong on GitHub and it needs to be `base href=""`, isnt't that what the `basePath` supposed to do?

![image](https://github.com/ghiscoding/aurelia-slickgrid/assets/643976/a0c1f2f9-faf1-4559-9e22-55f74b8a04f5)

It's getting late and I'll check that a bit more tomorrow but for now, I have to manually change it into my `gh-pages` branch and the remove the slash manually. I would hope to fix the automatic code published without the slash in the future

**Comment by MaximBalaganskiy** [comment]
Try "."

**Comment by ghiscoding** [comment]
didn't work either, same result. I'll post a comment on discourse

![image](https://github.com/ghiscoding/aurelia-slickgrid/assets/643976/f5c54c96-b4c5-4149-a300-46ed2a5a61c7)

**Comment by MaximBalaganskiy** [comment]
try specifuying the subfolder where github puts it, i think I've done that before with mdc lib

**Comment by ghiscoding** [comment]
this sux if we now have to do that, it was working fine in Au1

**Comment by MaximBalaganskiy** [comment]
Didi you try switvching to hash urls?
useUrlFragmentHash: true

**Comment by ghiscoding** [comment]
nope still the same result with a slash

**Comment by MaximBalaganskiy** [comment]
I have this in html
```html
<base href="">
```

**Comment by ghiscoding** [comment]
that didn't work for me but maybe I was something different in my webpack config that keeps adding the slash

**Comment by MaximBalaganskiy** [comment]
Have a look at my demo app, may be something can be picked https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/tree/v2/packages/app

**Comment by ghiscoding** [comment]
ahhh I found the issue, in my index.html, there a static base href defined, when even though I thought that it was added by WebPack, that wasn't the case...oops

**Comment by ghiscoding** [comment]
so you also have a base href defined in yours but you set it to empty. another thing that is different is that you are using `index.ejs` and I used to have that in my previous Au1 but you converted it to `index.html` in the Au2 PR so I taught ejs were no longer working... anyway, I can take another tomorrow, at least I got it working :)

I guess that's the default template that the new Au2 CLI produces, I'll convert it back to .ejs then

Thanks for the help

**Comment by ghiscoding** [comment]
@MaximBalaganskiy 
Hey to bother you again, so I'm trying to upgrade the demo and keep only the WebPack demo but it's not going so well. I'm getting problem loading the Aurelia-Slickgrid plugin at all. The project is working fine as standalone but when trying to load it externally, some of the DI aren't getting loaded. Would you have clue or pointer of what the problem might be? Is it my demo conversion (I didn't use the CLI, I just tried to convert by hand), or is it something else? I've opened a PR in the demo project [here](https://github.com/ghiscoding/aurelia-slickgrid-demos/pull/66) and below is a video of what the DI currently loads. I'm a little unfamiliar with the new plugin approach in Au2

![brave_kizCYwVPyz](https://github.com/ghiscoding/aurelia-slickgrid/assets/643976/23b8a6f5-2996-4b6e-a6ec-23d4039b8609)

**Comment by MaximBalaganskiy** [comment]
The project installs 
<img width="220" alt="image" src="https://github.com/ghiscoding/aurelia-slickgrid/assets/3712700/97d791cd-6c3c-4aeb-89b0-c8ad99f8824a">

**Comment by MaximBalaganskiy** [comment]
sorry, wrong branch

**Comment by ghiscoding** [comment]
I might have released v7 a little too early, oh well... I was thinking about possibly using pnpm workspaces in the future to properly 
separate the lib from the demo and, that might be a good time to work on that.

**Comment by MaximBalaganskiy** [comment]
I think you're not building the plugin correctly.
It either has to be a webpack build, as CLI scaffolds it, or you need to bend over your back with gulp (as I did, and regret it now)

**Comment by MaximBalaganskiy** [comment]
The way I had it in my initial conversion branch is the right way to do it.

**Comment by ghiscoding** [comment]
hmm I reverted some code in this [commit](https://github.com/ghiscoding/aurelia-slickgrid/commit/17eb5e8ae92220870761e3c40404d3d6e140b310) because all the Types were missing, does that previous include the code you were expecting then?

**Comment by MaximBalaganskiy** [comment]
It was in the very first branch where I basically started a new plugin with CLI.
Later I switched to updating your branch

**Comment by MaximBalaganskiy** [comment]
Also, a hint, add this file to your projects to avoid TS html errors
https://github.com/aurelia-ui-toolkits/aurelia-mdc-web/blob/v2/packages/app/src/resource.d.ts

**Comment by MaximBalaganskiy** [comment]
Here is that very first branch https://github.com/MaximBalaganskiy/aurelia-slickgrid/tree/au2
It uses webpack to build the plugin

**Comment by ghiscoding** [comment]
ok great that's helpful, I think I'll definitely have to go with the pnpm workspace to make sure it all works correctly. Thanks a lot for all these infos

**Comment by MaximBalaganskiy** [comment]
Not sure about `pnpm`, normal npm works just fine with workspaces. But that's really unrelated. The main issue is the build script of the plugin

**Comment by ghiscoding** [comment]
> Not sure about `pnpm`, normal npm works just fine with workspaces. But that's really unrelated. The main issue is the build script of the plugin

So I went ahead and started migrating to pnpm workspaces (with the current open PR), the reason is mostly because when using the [`workspace:`](https://pnpm.io/workspaces), it uses the build files (dist) and the `package.json` with its `main` with all exports, types and everything. It's pretty much like if we were doing an npm install with dist install and all but it's all happening locally without having to publish anything... So anyway, going with that approach and I can see that it's close to work but not quite. I'm having some issues with the WebPack plugin build and I also tried running similar build with esbuild and the result is quite similar but not exactly the same.

with WebPack I'm getting this error `Error: IAurelia`
![image](https://github.com/ghiscoding/aurelia-slickgrid/assets/643976/d4b9b153-71b6-425c-b53b-c23041f37050)

with esbuild I'm getting this error `Error: IDirtyChecker`
![image](https://github.com/ghiscoding/aurelia-slickgrid/assets/643976/29642c4e-6b09-43e8-93b0-c53d92a3ac8c)

The next step I've done was to look git clone the old commit you've referenced, which is this [commit](https://github.com/MaximBalaganskiy/aurelia-slickgrid/blob/3f9b56602fd8abb7f37d1616da425a738130fa24/index.html) and you said it works, well it's not entirely true, it does work running it from the `src/index` but it doesn't work if you run the build and change the `dev-app/main.ts` with the code shown below

```diff
- import * as Plugin from "../src/index";
+ import * as Plugin from "../dist/index"; // use build from dist

Aurelia
  .register(I18nConfiguration, Plugin, RouterConfiguration.customize({ useHref: false }), Example19DetailView, Example19Preload)
  .register(DecimalValueConverter, StringifyValueConverter, DateFormatValueConverter)
  .app(MyApp)
  .start();
```
with this I'm getting the exact same error as above with my code that is up to date, I'm getting `Error: IAurelia` and I don't really what to do to go further. The stack trace is coming from Aurelia, so there 0 info to help. You can try it yourself from your old commit and see for yourself. Any more suggestions on what else to do so that I can get over this error?

**Comment by MaximBalaganskiy** [comment]
This seems to have something to do with duplicate Aurelia imports.
Not sure how to correctly generate mjs modules with webpack.
Spent the whole day playing with vite and advanced to a point where slickgrid does not want to create an instance
because container is not in the DOM.

**Comment by MaximBalaganskiy** [comment]
Managed to get it working but.... had to switch to vite

**Comment by MaximBalaganskiy** [comment]
If you give me permission to this branch I can push my current working code

**Comment by ghiscoding** [comment]
Hi there, I added you as contributor so you should have access now (I don't know how else to give branch access). 

I do like Vite, so if we need Vite to get it working that's totally fine with me but is it just for creating/building the Plugin or does the end user also need Vite? I thought Au2 didn't support Vite yet? I stopped using WebPack and switched to Vite in my other projects

> On the other hand, you can use approach from AU2 MDC library with gulp.

I'm not sure I want to go back to Gulp really, I dropped that long time ago when npm scripts became more popular. What did you use it for anyway? I'll take a look after work to your Gulp usage

> Another option is to build with tsc and enable aurelia loader for the plugin in the consumer app. Currently node modules are excluded from html rule, you'll need to add an exception for the plugin folder

Is that again for the Plugin build only or for the end user? 

I really don't know what to do, so all the help you can give me is more than appreciated. I'd really like to finish this before Christmas :D

**Comment by MaximBalaganskiy** [comment]
I'll push the vite option then. The consumer can keep using webpack, that'll work.

**Comment by ghiscoding** [comment]
I've reopened the issue since it's not fixed yet and you can reference it in your upcoming PR.

Hey so I just saw that Sayan posted his own small datagrid on Aurelia discourse and taking a look at his build scripts, it looks like he's using TypeScript build directly with extra HTML/CSS files and that's about it, he's doesn't have any extra build scripts using WebPack or anything else. 

From his [`package.json`](https://github.com/Sayan751/au2-data-grid/blob/main/package/package.json), I see these scripts

```ts
"build:ts": "tsc",
"build:other": "cpx ./src/**/*.{html,css} ./dist",
"build": "run-p build:ts build:other",
```

I think 1 difference that I saw is that he's not using plugin directly but he has a `createConfiguration` function in his [configuration.ts](https://github.com/Sayan751/au2-data-grid/blob/main/package/src/configuration.ts) file. 

Going back to using pure TypeScript would be easier, but a Vite build would work too. As long as I'm getting it to work, that's the ultimate goal I guess :D but it's helpful to look at how a core team member does it. Perhaps it's just my folders and files that is different and should be adjusted?

**Comment by MaximBalaganskiy** [comment]
Simple compilation works, but requires a loader configuration in a consumer app. There's no way around this - au2 compiles html into js

**Comment by ghiscoding** [comment]
ah yeah looking at Sayan's lib on [unpkg](https://unpkg.com/browse/@sparser/au2-data-grid@1.0.0-rc.1/dist/), he does have html files in the `dist` folder but I agree with you that having the html compiled in the JS file is better. However the only html file in here is `aurelia-slickgrid.html`, I don't have html anywhere else since all the html in Slickgrid-Universal is dealt with native JavaScript.

**Comment by MaximBalaganskiy** [comment]
In this simple.case we can just add a template in vm file

**Comment by ghiscoding** [comment]
Yeah so can we just use code like this?

```ts
@customElement({
    name: 'app-loader',
    template: '<p>Loading...</p>'
})
```
will that code be native without requiring an html loader?

**Comment by MaximBalaganskiy** [comment]
Yes
