### ISSUE TITLE
Issues upgrading from v3.12.1 to v4.1.3

### ISSUE THREAD

**Issue by firstfocus** [ghiscoding/aurelia-slickgrid#787]
### Describe the bug

Hi, 
This plugin has been great so far - thanks for all your work on it. I have been using V3 for years. Recently I upgraded to V4, V4.1.3 and I have suddenly getting unexplained app-router errors. 

I'm using aurelia-framework@1.4.1, all my other packages seem up to date, I have been simplifying the grids I use to almost nothing, but the grid does not seem to get rendered and on-aurelia-grid-created.delegate does not get called. Instead I get the error below. The only difference in my code base is upgrading to V4. If I downgrade back to v3.12.1 all issues are gone, grids function as expected. This is the error from the router??

aurelia-logging-console.js?dc89:45 ERROR [app-router] TypeError: element.addEventListener is not a function
error @ aurelia-logging-console.js?dc89:45
aurelia-logging-console.js?dc89:45 ERROR [app-router] Router navigation failed, and no previous location or fallbackRoute could be restored.
error @ aurelia-logging-console.js?dc89:45

I'm at a loss atm. Any idea on how to best go about debugging this? I would really like to upgrade to V4.
Kind regards and thanks for your time.

### Reproduction

Upgrade from v3.12.1 to v4.1.3 with my code base, but not sure how to check for conflicts.

### Environment Info

```shell
Mac OSX
Aurelia 1.4.1
Slickgrid v3.12.1 and v4.1.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/aurelia-slickgrid/wiki/HOWTO--Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/aurelia-slickgrid/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/aurelia-slickgrid/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
hey thanks for using the lib, looking at this is not enough for me to provide much help. The things that I would suggest are the following
- have you followed the [Migration Guide to 4.x](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Migration-to-4.x)
- have you compared with [aurelia-slickgrid-demos](https://github.com/ghiscoding/aurelia-slickgrid-demos), which are always updated, by doing a prod build, on each new release of Aurelia-Slickgrid.
- have you update all Slickgrid-Universal packages, if you have any? This is often a problem, Aurelia-Slickgrid and Slickgrid-Universal packages are always updated the same day because they are inter-dependent on each other. 

Without a repro it's kinda hard to help here, you also didn't mention which bundler you're using (in my case, I'm more familiar with WebPack)... maybe 1 last thing to mention is that I know that Aurelia team updated some of their packages recently and I might not have them updated on my end, so I'm not sure if anything broke, perhaps you can compare with `aurelia-slickgrid-demos` and use same versions?

**Comment by ghiscoding** [comment]
closing since no feedback provided, as far as I know the lib is working fine with latest Aurelia 1.x dependencies. I have also put in place Renovate to update dependencies every week and so I would know quickly if any dependency is causing an issue
