### ISSUE TITLE
Pre-Release of version 2.x

### ISSUE THREAD

**Issue by ghiscoding** [ghiscoding/aurelia-slickgrid#81]
This is just a tracker
- [x] update all necessary Wikis
- [x] finish Slider Filter
- [x] finish Slider Editor (ref PR #80)
- [ ] Review Wiki mentioned in next paragraph

After Release 
- [x] Advertise Aurelia-Slickgrid on the [Awesome Aurelia](https://github.com/aurelia-contrib/awesome-aurelia) libraries list

**Comment by ghiscoding** [comment]
@jmzagorski 
I started updating all the Wikis and I am unsure about the Custom Filter on this [section](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Custom-Filter#how-to-use-custom-filter) at number 2  and also unsure about this [paragraph](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Custom-Filter#overriding-our-default-filters). Would you mind reviewing and update the doc, whenever you have a chance. Thanks

**Comment by ghiscoding** [comment]
@jmzagorski 
Finally done updating all Wikis, there's only the 2 paragraphs that I'd like your help in reviewing. There's no rush but I'd like that done eventually.

I'm planning a Final `2.x` Release by Monday

**Comment by ghiscoding** [comment]
@jmzagorski 
I officially released version [2.x](https://github.com/ghiscoding/aurelia-slickgrid/releases/tag/v2.0.1), updated all the necessary Wikis and updated the [GitHub Demo](https://ghiscoding.github.io/aurelia-slickgrid/#/slickgrid/)

However, I am still unsure about this paragraph in the [wiki](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Custom-Filter#how-to-use-custom-filter)
> Register your filter with the registerTransient method on the aurelia container in the startup file using the FILTER_PLUGIN_NAME the library exposes to register all of its filters. This registration is usually in main.ts or main.js. Then in your view model pass your custom filter's Filters property value to columnDefinition.filter.type property as a string. Here is that example:

If you have a chance, then please take a look at it, else I would assume it's good. I don't think many users would use that functionality anyway.

Thanks for all your help into making what is Aurelia-Slickgrid now. 🎉 🥇 😃

**Comment by jmzagorski** [comment]
@ghiscoding sorry I meant to review what you had asked yesterday, but my "outside work" life has gotten pretty busy since May.

I updated the wiki. We do not need to use FILTER_PLUGIN_NAME since we removed `columnDef.filter.type` and I do not think either are in the library anymore. Now they can pass their filter either with the new keyword or the uninstantiated class export (like they do for the `editor.model`) and aurelia will instantiate whatever they pass us. Users should register as transient still so we can leave that, although they could register it whatever they wanted and in most cases will get funky results on the grid

I also removed that other [paragraph](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Custom-Filter#overriding-our-default-filters) (see below for the original) you asked about since it was out of date and confusing. The wiki already explained that the user can override the default filter [here](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Custom-Filter#default-filter-type)

> 
> #### Overriding our default filters
> You are able to override our default supported filters if using `aurelia.container.registerSingleton(FILTER_PLUGIN_NAME, MyCustomFilter)`. Since our `Filter` interface has an optional `defaultFilter` property, you can set it to whatever you wish, and that means you can set it to one of our predefined [Filter enum](/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/filters/index.ts), you can choose any of them and override the `defaultFilter` in your [Global Grid Options](/ghiscoding/aurelia-slickgrid/wiki/Global-Options).

**Comment by ghiscoding** [comment]
@jmzagorski 
Thanks for reviewing, we can all breathe now version `2.x` is out haha. 
But seriously, again a big thanks for all your hard work and go have fun now, summer is not all year (not on my side anyway), so go out and have fun 🌞 🏖  

I also did publish it on Awesome Aurelia, it would be nice if we can get more downloads and traffics :)

**Comment by jmzagorski** [comment]
thanks and great work as well. I enjoy working on this library. Hopefully i can integrate it into more apps.

Big thanks for letting me know about that Awesome Aurelia repo. I did not know about that 👍

**Comment by ghiscoding** [comment]
I didn't know either, I only found out about it last week while looking at the [aurelia-contrib](https://github.com/aurelia-contrib). The Awesome Aurelia does have a nice list, waiting for the PR to be merged, hopefully will bring more traffics :)

Cheers
