### ISSUE TITLE
Creating a filter factory to create new filters in the filter.service

### ISSUE THREAD

**Issue by jmzagorski** [ghiscoding/aurelia-slickgrid#9]
I was reviewing your prior commits and saw you improved the filtering by adding a [filter interface](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/models/filter.interface.ts). I think we can take this one step further by using a factory to create the filters and allow Aurelia to inject any number of dependencies that are needed in the filters. I'll explain with current vs future state below:

Current State:
In the [filter interface](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/models/filter.interface.ts) you manually instantiate a filter using a `switch(filterType)` and passing in the i18n service that is injected into the `FilterService`.

Future State:
1. We add a property on the `Filter` interface that requires every Filter implementation to have a `FilterType` value (ie the `SelectFilter` would have `filterType = FilterType.select`. 
2. We code a new `FilterFactory` such as:

```typescript
@inject(All.of('GridFilters'))
export class FilterFactory {

constructor(private filters: Filter[]) {}

public createFilter: Filter (filterType: string) {
  return this.filters.find(f => f.filterType === filterType);
  // or throw an exception if a filter is not found
}
```
3. Tell Aurelia about our new objects in `main.ts`:

```
aurelia.container.registerSingleton('GridFilters', InputFilter);
aurelia.container.registerSingleton('GridFilters', SelectFilter);
aurelia.container.registerSingleton('GridFilters', SingleSelectFilter);
aurelia.container.registerSingleton('GridFilters', MultipleSelectFilter);
```

Benefits: 
1. This allows Aurelia to handle the dependency graphs for each filter. This means we can inject any number of dependencies into the filters without bloating the `FilterService`. This is a huge benefit. One example I can think of is using the `BindingEngine` from `aurelia-framework` to watch the `collection` property on the select list filters ( :-) could be a future pull request). Right now the library assumes this `collection` will have all the data when the view model is ready. However, what if the consumer is using a [generator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators) instead of a promise, or they are fetching the data at some later time after the view model is already created or what if the consumer deletes a record in the grid that was in the select filter and should no longer be in the select filter (sorry for going off on tangent, but I have thought about this for a few days)

2. No longer need to inject the i18n in the  [filter interface](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/models/filter.interface.ts) since its only purpose was to pass it to the filters. Now we just need to inject the `FilterFactory`

3. Removes the responsibility of creating the filters from the `FilterService`. That means if we support another filter such as a [datalist](https://www.w3schools.com/tags/tag_datalist.asp) ( :-) I already thought of this for a future pull request) then we only have to create the DatalistFilter interface and add the filter to the list of 'GridFilters' in the `main.ts`. Then, there would be no to little change in the `FilterService`. 

I can create this feature since I've done this in a deprecated project of mine https://github.com/jmzagorski/allforms/blob/master/src/main.js

**Comment by ghiscoding** [comment]
Thanks, this is nice to read and very instructive. There's a lot of what you wrote in there that I had in mind for the future indeed. On my work project, there was a big requirement for a multiple select filter which is why I worked on that, however I do feel there could be some improvements in the future. Anyhow, I can't just work on grid features, we still have to build the App and ship something, but here's a few thing I had in mind too:

1. I wasn't crazy about the fact that I have to do `new xFilter()` inside the Service or outside in a component (VM) and I did it that way for now to get it out the door. Plenty of room for improvement indeed.
  - Also, the `filter` property is different compare to the inline `editor` in which the latter also uses a class but doesn't need to create a `new` instance, I assume SlickGrid does it internally. However in TypeScript, it doesn't let me just reference it and instantiate it later. 

2. The `collection` is also something that I want to eventually fill with/without Promise, but again I had to ship the feature and I thought I could come back to it later. For now in Angular, I resolve the collection before going in the page and it's manageable but it would be nice to simply call it with a Promise or Observable in Angular.
- I never saw anyone else do other type of filters like I did (in the Header Row I mean). Even my first couple years of working with SlickGrid, I always had used only `input text` filter. So I'm quite happy that I now have multiple Filter types. Though at the end of the day, it's restricted to htmp+js lib.

For some of the points you wrote
1. I'm not familiar with `registerSingleton` and `Factory`, so if it helps in my point 1) that I wrote on top, then yes please go ahead with it. You are lucky enough to work with only 1 framework, I wish I could use only Aurelia and get to know it better :S

2. I inject the `i18n` Service because I need it for translation (at work all our Apps must be English/French). If you have another way to do it, I assume Depency Injection? As long as I can still deal with translations in the Filters, then I'm good with the changes.

3. `datalist`, wow I never heard about these, such a shame. That does look like a typeahead functionality though. Anyhow, I renamed `selectOptions` to `collection` to make it more generic for these kind of situations, you want to use a collection but it might not be for a Select dropdown. This datalist might be another Filter type though. If you want to make it part of the lib (instead of a Custom Filter), then I'm open for that too. 

There's a lot for me to learn, but I'm totally open for changes if it make sense and help develop. I'm still oriented into shipping all features that I first need, then possibly coming back to refactor some pieces (like the Filters not supporting Promises).

**Comment by jmzagorski** [comment]
thanks for the great feedback. I have one small pull request to submit to you (it changes one line of code lol) and then I will work on this to see if it works in practice.

Hopefully I didn't bring more confusion to this issue by saying `Factory`. I meant it in terms of the [Factory Pattern](https://en.wikipedia.org/wiki/Factory_%28object-oriented_programming%29). Not to be confused with Aurelia's [Factory Resolver](http://aurelia.io/docs/fundamentals/dependency-injection#resolvers)

**Comment by ghiscoding** [comment]
So that `datalist` got me curious and it looks interesting for a new Filter type, however I found it's not supported in Safari but there's maybe this [purejs-datalist polyfill](https://github.com/Fyrd/purejs-datalist-polyfill) or this other one that he got inspired from [jquery datalist polyfill](https://github.com/CSS-Tricks/Relevant-Dropdowns) that could be used.

**Comment by jmzagorski** [comment]
Yup, if you are supporting safari then the plain old HTML datalist wont do. I have used https://twitter.github.io/typeahead.js/ if you are looking at evaluating typeahead libraries

**Comment by ghiscoding** [comment]
Talking about Filters, I also have this in mind. A Filter that could support compound filter (operator + value). Currently in my lib, you can Filter values with an operator (like `>=50`) inside the input text Filter, but it's not obvious to the users that they can do that, unless they know about it. That's were this compound filter would be nice and we could combine this with a Date Filter (which I plan to use `Flatpickr` since it's already part of my lib). That would be really awesome... future plan :)

I would actually have to operator on the left though

![image](https://user-images.githubusercontent.com/643976/36560954-521f76fe-17e0-11e8-8bf1-1ff6ae29ab4b.png)

**Comment by jmzagorski** [comment]
Before I close this, do you want me to open up two more issues for a Datalist/typeahead filter and a `Compound` filter?

**Comment by ghiscoding** [comment]
We can open new issues for something that we plan to address in the coming weeks, but I'm not sure if we will ever get to the compound filter. Basically I don't mind opening issues for something that we will work on, but not for something might never be addressed. I assume you will do the Datalist/Typeahead, so yeah you can open an issue and reference it later.
