### ISSUE TITLE
[Bug] Pressing tab while in single/multiple select editor leaves the select list open

### ISSUE THREAD

**Issue by jmzagorski** [ghiscoding/aurelia-slickgrid#92]
**I'm submitting a bug report**

* **Library Version:**
Current

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Browser:**
all
* **Language:**
TypeScript

**Current behavior:**
If the select list is open and a user hits tab, the select list remains open. If you try to select a value nothing happens since tab has activated the next cell

**Expected/desired behavior:**

* **What is the expected behavior?**
The select list closes

* **What is the motivation / use case for changing the behavior?**
It is really not a big bug, but makes the user experience better if the select list went away or if tab did nothing, whichever you thought was better

**Comment by ghiscoding** [comment]
I assume you will eventually come up with a PR?

**Comment by jmzagorski** [comment]
Yes. I should have mentioned that I was submitting that so I would not forget about it.

**Comment by ghiscoding** [comment]
@jmzagorski 
I'm ready to release a new version (almost a month without any), which will include the major refactor of `collectionAsync` and the new PR #93 (autoAdjust drop height, width & position), the latter is a huge improvement, more detail in the PR #93 

All that to say, do you have something in the queue for the new version or should I release without waiting? If not I'll release before Friday.

Also wondering why we're losing votes, 2 in a week, instead of gaining. I'm not sure if it's unit testing or number of opened issues (or both) that scares them away. Anyhow, I've gained many more in my other repo `Angular-Slickgrid`, which just reached 40 stars. Too bad Aurelia isn't lighting up more, though I'm very well interested in their complete rewrite of vNext (with TypeScript 3.0). These lost users seriously makes me think that I should spend time on other things, like my personal project with the grid. I'll probably delete this last paragraph in a few days, just had to let it out.

**Comment by ghiscoding** [comment]
I've done the release of version [2.3.0](https://github.com/ghiscoding/aurelia-slickgrid/releases/tag/v2.3.0) over lunch. It's mainly all done, both demos were also updated, only thing left is the Wiki to be updated which could be today or tomorrow.
